---
abstract: 'RDF view for your data'
author:
  - 'Thiago Rondon <thiago@aware.com.br>'
build_requires:
  Catalyst: 0
  Catalyst::Controller: 0
  Catalyst::Test: 0
  Encode: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  FindBin: 0
  HTTP::Request::AsCGI: 0
  MRO::Compat: 0
  RDF::Simple::Parser: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200007, CPAN::Meta::Converter version 2.110440'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-View-RDF
requires:
  Catalyst::View: 0
  Moose: 0
  RDF::Simple::Serialiser: 0
resources:
  bugtracker: http://github.com/maluco/Catalyst-View-RDF/issues
  repository: git://github.com/maluco/Catalyst-View-RDF
version: 0.01
